project_id = "kdskhwtqtrwqvdexcjeh"

[functions.analyze-meal]
verify_jwt = true

[functions.generate-recipes]
verify_jwt = true

[functions.ai-assistant]
verify_jwt = false

[functions.send-scheduled-notifications]
verify_jwt = false

[functions.generate-trainer-plan]
verify_jwt = true

[functions.push-public-key]
verify_jwt = false

[functions.push-subscribe]
verify_jwt = true

[functions.validate-receipt]
verify_jwt = true

[functions.generate-weekly-plan]
verify_jwt = true
